### ISSUE TITLE
crash in singleplayer while exiting world

### ISSUE THREAD

**Issue by erisdev** [Gerflargle/TaffyShield#1]
Seems to happen if the window gets resized while the world is saving or loading... weird. I can't reliably reproduce it, but when it happens, it happens under those circumstances.

[crash-2020-05-12_21.24.27-client.txt](https://github.com/Gerflargle/TaffyShield/files/4619278/crash-2020-05-12_21.24.27-client.txt)

**Comment by Gerflargle** [comment]
hrm.. I will take a look into it. Thanks for letting me know.

**Comment by Gerflargle** [comment]
I couldn't reproduce it [yet?], however, I did add in two null checks in hopes that it might catch those odd cases. 
Would you mind trying this file? (Sorry, I had to zip it as git wouldn't let me do the jar directly. Just extract the zip and then drop the jar in like normal)

[taffyshield-1.15.2-0.2.zip](https://github.com/Gerflargle/TaffyShield/files/4622827/taffyshield-1.15.2-0.2.zip)

**Comment by erisdev** [comment]
Oh, sure thing, give me a moment.

**Comment by erisdev** [comment]
Still seems to be having the issue:

- with forge 30.1.42: [crash-2020-05-14_15.30.06-client.txt](https://github.com/Gerflargle/TaffyShield/files/4630472/crash-2020-05-14_15.30.06-client.txt)
- with forge 30.1.0: [crash-2020-05-14_15.41.51-client.txt](https://github.com/Gerflargle/TaffyShield/files/4630512/crash-2020-05-14_15.41.51-client.txt)

**Comment by Gerflargle** [comment]
Ok, thanks for checking. Would you mind trying this one? 
I was able to cause the error locally and I think this one may fix it. 

[taffyshield-1.15.2-0.3.zip](https://github.com/Gerflargle/TaffyShield/files/4630919/taffyshield-1.15.2-0.3.zip)

**Comment by erisdev** [comment]
Oh yes, this appears to work perfectly! Thank you so much, and sorry it took me so long to get back to you! I'm actually curious what was happening

**Comment by Gerflargle** [comment]
Not a problem. Thank you for confirming it works.
